<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU2qY86v\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU2qY86v/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU2qY86v.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU2qY86v\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU2qY86v\App_KernelDevDebugContainer([
    'container.build_hash' => 'U2qY86v',
    'container.build_id' => 'fb23500e',
    'container.build_time' => 1707482325,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU2qY86v');
